- name: Reload sysctl
  ansible.builtin.command: sysctl --system
  changed_when: false

- name: Restart pve-firewall
  ansible.builtin.service:
    name: pve-firewall
    state: restarted
  changed_when: false
